### ISSUE TITLE
dbGetInfo does not return Port number and Server Name does not match for MSSQL

### ISSUE THREAD

**Issue by edgararuiz** [rstats-db/odbc#51]
### Issue Description and Expected Result

dbGetInfo does not return Port number and Server Name does not match for MSSQL

### Database

SQL Server 2012

### Reproducible Example

```
odbcSQLSeverCon <- dbConnect(odbc(),
                             Driver              = "SQL Server Driver",
                             Server              = "sol-eng-sqlserv.cihykudhzbgw.us-west-2.rds.amazonaws.com",
                             Database            = "airontime",
                             UID                 = "rstudioadmin",
                             PWD                 = "[PRIVATE]",
                             Port                = 1433)


DBI::dbGetInfo(odbcSQLSeverCon)
```

Results in this:

```
$dbname
[1] "airontime"

$dbms.name
[1] "Microsoft SQL Server"

$db.version
[1] "12.00.4422"

$username
[1] "rstudioadmin"

$host
[1] ""

$port
[1] ""

$sourcename
[1] ""

$servername
[1] "EC2AMAZ-O5QKKM8"

$drivername
[1] "RStudio SQL Server ODBC Driver"

$odbc.version
[1] "03.52"

$driver.version
[1] "1.3.8.1031"

$odbcdriver.version
[1] "03.80"

$supports.transactions
[1] TRUE

attr(,"class")
[1] "Microsoft SQL Server" "driver_info"          "list"    
```
Even though I'm passing port number it comes back empty in dbGetInfo

**Comment by jimhester** [comment]
I I included these fields because they are mentioned in the DBI documentation for [`dbGetInfo()`](https://www.rdocumentation.org/packages/DBI/versions/0.5-1/topics/dbGetInfo) and tested to exists in DBItest, but as far as I can tell [`SQLGetInfo()`](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function) does not allow one to query the host or port, which is why they are empty strings.

We could potentially populate them from input parameters, but as they are non-standard and depend on the driver it would only work some of the time.
